### ISSUE TITLE
 Send key Power off does not work

### ISSUE THREAD

**Issue by Vincent75b** [balmli/com.samsung.smart#12] opened 2019-04-02 17:01 UTC
On Samsung the frame 2018. Command might be different for this type of tv because of the ‘art mode’?

Tried it to give a 5 sec power off signal to turn the tv completely off

I can turn the tv on and in art mode from the app (icon) (and vice versa)

Send key Power Toggle does work!

**Comment by balmli** [comment] 2019-04-02 18:26
See #10

**Comment by balmli** [comment] 2019-04-02 18:29
I close this issue, since it's a duplicate of #10

**Closed by balmli** 2019-04-02 18:29 UTC
